export { default as Capsule } from './Capsule'
export { default as Circle } from './Circle'
export { default as Plate } from './Plate'
export { default as Polygon } from './Polygon'
export { default as Rectangle } from './Rectangle'
export { Shape } from './type'
